---
- name: DR Recovery - Levantar VM caida en Azure
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Autenticar con Managed Identity
      uri:
        url: "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/"
        headers:
          Metadata: "true"
        method: GET
      register: auth_response

    - name: Extraer token
      set_fact:
        access_token: "{{ auth_response.json.access_token }}"

    - name: Levantar vm-target-dr
      uri:
        url: "https://management.azure.com/subscriptions/1fefe992-e8e2-472d-bb8a-bac89bf7b525/resourceGroups/rg-monitoreo/providers/Microsoft.Compute/virtualMachines/vm-target-dr/start?api-version=2023-03-01"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        status_code: [200, 202]
      register: start_result

    - name: Reportar resultado
      debug:
        msg: "VM vm-target-dr iniciada exitosamente"

    - name: Notificar resultado a Power Automate
      uri:
        url: "https://default95028a14d2f943c0bc7342a4be7c04.92.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/234e03f98e064bc19eed5b1b3daf796f/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=AME72QUsPPNekXE5plbxq1PLdMBIvAUsEZ7WthyT8Zo"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          status: "success"
          vm: "vm-target-dr"
          mensaje: "VM vm-target-dr levantada exitosamente"
          duracion: "{{ lookup('pipe', 'date +%H:%M:%S') }}"
